employees = [
    {
        "id": 1,
        "name": "Ravi Kumar",
        "age": 28,
        "department": "IT",
        "role": "Software Engineer",
        "salary": 75000,
        "email": "ravi.kumar@company.com",
    },
    {
        "id": 2,
        "name": "Akarsh",
        "age": 30,
        "department": "HR",
        "role": "HR Manager",
        "salary": 65000,
        "email": "akarsh@company.com",
    },
    {
        "id": 3,
        "name": "Rahul Verma",
        "age": 26,
        "department": "Finance",
        "role": "Financial Analyst",
        "salary": 70000,
        "email": "rahul.verma@company.com",
    },
    {
        "id": 4,
        "name": "Kiran Patel",
        "age": 32,
        "department": "Marketing",
        "role": "Marketing Lead",
        "salary": 68000,
        "email": "kiran.patel@company.com",
    },
    {
        "id": 5,
        "name": "Sneha Reddy",
        "age": 27,
        "department": "IT",
        "role": "DevOps Engineer",
        "salary": 80000,
        "email": "sneha.reddy@company.com",
    },
]
